const productos = [
  {
    id: 1,
    nombre: "Cuadernillo ABC",
    descripcion: "Cuadernillo rayado",
    descripcionLarga: "Cuadernillo rayado de 50 hojas, ideal para niños que están aprendiendo a escribir. Papel de buena calidad y tapas blandas resistentes.",
    categoria: "niños",
    precio: 5500,
    stock: 9,
    img: "./../../assets/img/cuadernillo_rivadavia.jpg",
    cantidad: 0,
  },
  {
    id: 2,
    nombre: "Set de lapiceras",
    descripcion: "Set de 2 lapiceras azules",
    descripcionLarga: "Lapiceras de tinta azul, punta fina de 1.0mm, cómodas para escritura diaria. Perfectas para el colegio o la oficina.",
    categoria: "boligrafos",
    precio: 3000,
    stock: 20,
    img: "../../assets/img/boligrafo-bic-cristal-2-bdda19b556069ae92617044031764811-640-0.jpg",
    cantidad: 0,
  },
  {
    id: 3,
    nombre: "Cartulinas",
    descripcion: "Amplia variedad de colores",
    descripcionLarga: "Pack surtido de 50 cartulinas tamaño A4 en colores vivos. Ideal para manualidades, proyectos escolares y presentaciones.",
    categoria: "libreria",
    precio: 10000,
    stock: 30,
    img: "../../assets/img/cartulina.jpg",
    cantidad: 0,
  },
  {
    id: 4,
    nombre: "Globo terráqueo",
    descripcion: "Tamaño ideal para preparar tus clases",
    descripcionLarga: "Globo terráqueo con soporte de madera y detalles geográficos actualizados. Perfecto para estudios escolares y decoración de oficina.",
    categoria: "libreria",
    precio: 30000,
    stock: 2,
    img: "../../assets/img/globo_terraqueo.jpg",
    cantidad: 0,
  },
  {
    id: 5,
    nombre: "Juguete interactivo",
    descripcion: "Juguete de clasificación de formas",
    descripcionLarga: "Juego de encastre con bloques de distintas formas y colores. Estimula la motricidad fina y el reconocimiento de figuras.",
    categoria: "niños",
    precio: 7000,
    stock: 10,
    img: "../../assets/img/juego_interactivo.png",
    cantidad: 0,
  },
  {
    id: 6,
    nombre: "Resaltadores Fluorescentes",
    descripcion: "Pack de 6 colores",
    descripcionLarga: "Set de resaltadores de colores vibrantes con tinta a base de agua. No traspasan el papel y son ideales para el estudio.",
    categoria: "libreria",
    precio: 5500,
    stock: 15,
    img: "../../assets/img/resaltadores.jpg",
    cantidad: 0,
  },
  {
    id: 7,
    nombre: "Mochila Escolar",
    descripcion: "Mochila con compartimentos",
    descripcionLarga: "Mochila ergonómica con varios bolsillos, espacio para notebook y material escolar. Correas acolchadas para mayor comodidad.",
    categoria: "niños",
    precio: 25000,
    stock: 7,
    img: "../../assets/img/mochila.jpg",
    cantidad: 0,
  },
  {
    id: 8,
    nombre: "Calculadora Científica",
    descripcion: "240 funciones",
    descripcionLarga: "Calculadora científica con pantalla de dos líneas, funciones trigonométricas y estadísticas. Ideal para secundaria y universidad.",
    categoria: "libreria",
    precio: 18000,
    stock: 12,
    img: "../../assets/img/calculadora.jpg",
    cantidad: 0,
  },
  {
    id: 9,
    nombre: "Tijera Escolar",
    descripcion: "Tijera de punta redonda",
    descripcionLarga: "Tijera de 13 cm con puntas redondeadas, especial para uso infantil. Hoja de acero inoxidable y mango ergonómico.",
    categoria: "niños",
    precio: 2000,
    stock: 25,
    img: "../../assets/img/tijera.jpg",
    cantidad: 0,
  },
  {
    id: 10,
    nombre: "Lápices de Colores",
    descripcion: "Caja de 12 unidades",
    descripcionLarga: "Lápices de colores brillantes y resistentes. Fáciles de afilar y con mina de 3mm para trazos intensos.",
    categoria: "niños",
    precio: 4500,
    stock: 18,
    img: "../../assets/img/lapices_colores.jpg",
    cantidad: 0,
  },
  {
    id: 11,
    nombre: "Agenda 2025",
    descripcion: "Agenda diaria con tapas duras",
    descripcionLarga: "Agenda con calendario anual, secciones para notas y marcadores de página. Tapas duras resistentes y diseño elegante.",
    categoria: "libreria",
    precio: 9500,
    stock: 10,
    img: "../../assets/img/agenda.jpg",
    cantidad: 0,
  },
  {
    id: 12,
    nombre: "Regla Acrílica",
    descripcion: "30 centímetros",
    descripcionLarga: "Regla de acrílico transparente de 30 cm. Resistente, ligera y con bordes rectos para mayor precisión.",
    categoria: "libreria",
    precio: 1500,
    stock: 40,
    img: "../../assets/img/regla.jpg",
    cantidad: 0,
  },
  {
    id: 13,
    nombre: "Corrector en Cinta",
    descripcion: "Corrector instantáneo",
    descripcionLarga: "Corrector en cinta de 5mm x 8m. Rápido secado, no deja manchas y permite reescribir inmediatamente.",
    categoria: "libreria",
    precio: 2500,
    stock: 30,
    img: "../../assets/img/corrector.jpg",
    cantidad: 0,
  },
  {
    id: 14,
    nombre: "Plastilina",
    descripcion: "Pack multicolor",
    descripcionLarga: "Set de plastilinas suaves y moldeables en colores básicos. Perfectas para trabajos manuales y actividades artísticas infantiles.",
    categoria: "niños",
    precio: 3200,
    stock: 20,
    img: "../../assets/img/plastilina.jpg",
    cantidad: 0,
  },
  {
    id: 15,
    nombre: "Pegamento Escolar",
    descripcion: "Barra adhesiva",
    descripcionLarga: "Pegamento en barra no tóxico de 20g. Ideal para papel, cartón y manualidades.",
    categoria: "libreria",
    precio: 1200,
    stock: 50,
    img: "../../assets/img/pegamento.jpg",
    cantidad: 0,
  },
  {
    id: 16,
    nombre: "Compás Metálico",
    descripcion: "Compás de precisión",
    descripcionLarga: "Compás metálico con tornillo de ajuste para mayor precisión. Incluye minas de repuesto.",
    categoria: "libreria",
    precio: 6000,
    stock: 15,
    img: "../../assets/img/compas.jpg",
    cantidad: 0,
  },
  {
    id: 17,
    nombre: "Libro Infantil",
    descripcion: "Cuento ilustrado",
    descripcionLarga: "Libro de cuentos ilustrados con tapa dura y páginas a color. Estimula la lectura y la imaginación.",
    categoria: "niños",
    precio: 8000,
    stock: 12,
    img: "../../assets/img/libro_infantil.jpg",
    cantidad: 0,
  },
  {
    id: 18,
    nombre: "Set de Gomas",
    descripcion: "Pack de 3 gomas de borrar",
    descripcionLarga: "Gomas suaves que no manchan el papel. Ideal para lápiz y portaminas.",
    categoria: "libreria",
    precio: 1800,
    stock: 35,
    img: "../../assets/img/gomas.jpg",
    cantidad: 0,
  },
  {
    id: 19,
    nombre: "Cuaderno Universitario",
    descripcion: "Cuaderno de 80 hojas",
    descripcionLarga: "Cuaderno universitario con tapa dura y anillado metálico. Papel de alta calidad y diseño moderno.",
    categoria: "libreria",
    precio: 6500,
    stock: 20,
    img: "../../assets/img/cuaderno.jpg",
    cantidad: 0,
  },
  {
    id: 20,
    nombre: "Rompecabezas",
    descripcion: "Puzzle de 500 piezas",
    descripcionLarga: "Rompecabezas de cartón rígido con ilustración colorida. Estimula la concentración y la memoria.",
    categoria: "niños",
    precio: 9500,
    stock: 8,
    img: "../../assets/img/rompecabezas.jpg",
    cantidad: 0,
  },
  {
    id: 21,
    nombre: "Mapa Político",
    descripcion: "Mapa mural plastificado",
    descripcionLarga: "Mapa político de Argentina plastificado, tamaño A1. Incluye divisiones provinciales y capitales.",
    categoria: "libreria",
    precio: 7000,
    stock: 10,
    img: "../../assets/img/mapa.jpg",
    cantidad: 0,
  },
  {
    id: 22,
    nombre: "Pinceles Escolares",
    descripcion: "Set de 5 pinceles",
    descripcionLarga: "Set de pinceles de distintos tamaños, con cerdas sintéticas y mango de madera. Perfecto para acuarelas y témperas.",
    categoria: "niños",
    precio: 4800,
    stock: 14,
    img: "../../assets/img/pinceles.jpg",
    cantidad: 0,
  },
  {
    id: 23,
    nombre: "Block de Hojas",
    descripcion: "Hojas rayadas A4",
    descripcionLarga: "Block de 100 hojas rayadas tamaño A4. Papel de 75g de alta resistencia.",
    categoria: "libreria",
    precio: 4000,
    stock: 22,
    img: "../../assets/img/hojas.jpg",
    cantidad: 0,
  },
  {
    id: 24,
    nombre: "Juego Didáctico",
    descripcion: "Juego de memoria",
    descripcionLarga: "Juego didáctico de memoria con tarjetas ilustradas. Ayuda al desarrollo cognitivo y la atención en niños.",
    categoria: "niños",
    precio: 6700,
    stock: 9,
    img: "../../assets/img/juego_memoria.jpg",
    cantidad: 0,
  },
  {
    id: 25,
    nombre: "Estuche Portatodo",
    descripcion: "Cartuchera escolar",
    descripcionLarga: "Cartuchera con doble cierre y compartimentos. Material resistente y diseño moderno.",
    categoria: "niños",
    precio: 5500,
    stock: 16,
    img: "../../assets/img/cartuchera.jpg",
    cantidad: 0,
  },
  {
    id: 26,
    nombre: "Revistero",
    descripcion: "Revistero de cartón duro",
    descripcionLarga: "Revistero organizador de cartón reforzado. Ideal para mantener ordenados tus papeles y carpetas.",
    categoria: "libreria",
    precio: 6000,
    stock: 12,
    img: "../../assets/img/revistero.jpg",
    cantidad: 0,
  },
  {
    id: 27,
    nombre: "Set de Clips",
    descripcion: "Caja de 100 clips metálicos",
    descripcionLarga: "Clips metálicos niquelados de alta resistencia. Mantienen el papel sujeto sin dañarlo.",
    categoria: "libreria",
    precio: 1500,
    stock: 40,
    img: "../../assets/img/clips.jpg",
    cantidad: 0,
  },
  {
    id: 28,
    nombre: "Pizarra Blanca",
    descripcion: "Pizarra magnética",
    descripcionLarga: "Pizarra blanca magnética de 60x40 cm. Incluye borrador y marcadores de colores.",
    categoria: "libreria",
    precio: 22000,
    stock: 5,
    img: "../../assets/img/pizarra.jpg",
    cantidad: 0,
  },
  {
    id: 29,
    nombre: "Set de Marcadores",
    descripcion: "Marcadores permanentes",
    descripcionLarga: "Pack de 4 marcadores permanentes con punta fina y tinta de larga duración. Funcionan sobre múltiples superficies.",
    categoria: "libreria",
    precio: 5200,
    stock: 18,
    img: "../../assets/img/marcadores.jpg",
    cantidad: 0,
  },
  {
    id: 30,
    nombre: "Atlas Escolar",
    descripcion: "Atlas geográfico ilustrado",
    descripcionLarga: "Atlas con mapas a color, ilustraciones y datos actualizados. Ideal para nivel primario y secundario.",
    categoria: "libreria",
    precio: 15000,
    stock: 6,
    img: "../../assets/img/atlas.jpg",
    cantidad: 0,
  }
];

export default productos;
